# Generated by Django 5.1.1 on 2024-09-21 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='district',
            field=models.CharField(default='malappuram', max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user_details',
            name='experience',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_details',
            name='gender',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='user_details',
            name='skill',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
