# Generated by Django 5.1.1 on 2024-09-21 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_details_district_user_details_dob_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='User_detail',
        ),
    ]
