# Generated by Django 5.1.1 on 2024-09-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_detail_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='user_id',
            new_name='user',
        ),
    ]
