# Generated by Django 5.1.1 on 2024-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_id_user_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='district',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
