# Generated by Django 5.1.1 on 2024-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_detail_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
