# Generated by Django 5.1.1 on 2024-09-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_dashboard_title_alter_dashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='profile_img',
            field=models.ImageField(default='profiles/default_profile.jpg', upload_to='profiles'),
        ),
    ]
