# Generated by Django 5.1.1 on 2024-09-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_detail_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='profile_img',
            field=models.ImageField(default='profiles/default_profile.jpeg', upload_to='profiles'),
        ),
    ]
