# Generated by Django 5.1.1 on 2024-10-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='work_img',
            field=models.ImageField(null=True, upload_to='job_image'),
        ),
    ]
