# Generated by Django 5.1.1 on 2024-10-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_job_post_work_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client'),
        ),
    ]
