# Generated by Django 5.1.1 on 2024-10-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_job_post_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='job_image/thumbnail'),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='work_img',
            field=models.ImageField(null=True, upload_to='job_image/'),
        ),
    ]
